version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'nutfes-record-db'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: ./api
    container_name: 'nutfes-record-api'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  view:
    build: ./view
    container_name: 'nutfes-record-view'
    command: npm run start
    ports:
      - "9000:9000"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - VUE_APP_URL=http://133.125.44.106:3001

volumes:
  mysql-data:
    driver: local
